### ISSUE TITLE
Abandoned Safehouse TTW.esm is missing

### ISSUE THREAD

**Issue by satorope** [wastelandsurvivalguide/wastelandsurvivalguide.github.io#1]
After installing the merged patch for Dynamic Weapon Displays, MO2 warns me that Abandoned Safehouse TTW.esm is missing from the master.
The reason may be that Abandoned Safehouse TTW is not included in the list of mods.

**Comment by wastelandsurvivalguide** [comment]
All fixed; Abandoned Safehouse is re-added to Content section.
