### ISSUE TITLE
There is a missing file written to loadorder

### ISSUE THREAD

**Issue by satorope** [wastelandsurvivalguide/wastelandsurvivalguide.github.io#2]
The following files are not listed in the loadorder.

Goodsprings and Powder Gangers Truce.esp
House and NCR Truce FPGE Patch.esp
TweaksTTW.esm

**Comment by wastelandsurvivalguide** [comment]
Fixed! Appreciate the help <3

**Comment by satorope** [comment]
https://wastelandsurvivalguide.com/docs/finish

"TweaksTTW.esm" is incorrectly written as "Tweaks TTW.esp".
Two files have not been added to the loadorder.

Goodsprings and Powder Gangers Truce.esp
House and NCR Truce FPGE Patch.esp

**Comment by satorope** [comment]
"TweaksTTW.esm" is incorrectly written as "Tweaks TTW.esm".
The filename contains a space.
