### ISSUE TITLE
Merge, replace or rename.

### ISSUE THREAD

**Issue by Jeanichou** [wastelandsurvivalguide/wastelandsurvivalguide.github.io#22]
I suggested to explain at the start of the Wasteland Guide what to do with "Merge, replace or rename." come up. This was understandably denied as it is already explained in The Best of Times, which this guide ask to refer to as having been previously learned. I will note however that what is said is said in The Best of Times, which include the explanation of what to do, is never actually used in the current version of that guide, so for more newbie (aka me) it's never actually learned in practice. Still think it could use a mention in the preface of the Wasteland Survivor guide but if not feel free to close.

**Comment by lctoye** [comment]
It used to be learned in practice during TBOT when user installed ShowOFF INI, but since that step has been removed, you have a valid point. I will very briefly mention it in the "Installing Mods" paragraph.
