### ISSUE TITLE
Capital Wasteland Hideouts Compatibility patch for SawyerBatty TTW

### ISSUE THREAD

**Issue by satorope** [wastelandsurvivalguide/wastelandsurvivalguide.github.io#6]
This mod is not on the list, is it unnecessary?

Capital Wasteland Hideouts Compatibility patch for SawyerBatty TTW

**Comment by satorope** [comment]
Thank you for adding this.
But this is not included in loadorder.txt.

**Comment by lctoye** [comment]
Heh whoops, I knew I forgot something. Will fix this when I have a chance, cheers.
