### ISSUE TITLE
NVTF ini

### ISSUE THREAD

**Issue by Friendlyx3** [wastelandsurvivalguide/wastelandsurvivalguide.github.io#8]
After downloading the newest version of NVTF I noticed when comparing ini files line 54 'b'TweakMiscRendererSafeGuard = 1 is 'i'TweakMiscRendererSafeGuard = 1 in the OG ini file. Is that intentional on your part?

**Comment by ghost** [comment]
Yes

**Comment by Friendlyx3** [comment]
I've looked on the ttw discord, a search engine, and NVTF's page on Nexus and can't seem to figure out why that was changed? I just want to make sure you read my OP correctly; btweak(WSG) itweak(original ini)

**Comment by ghost** [comment]
Oh sorry, i misread your comment. What i meant is that the change from a bool to int is intentional from NVTF. The custom INI from WSG is no longer a thing, we now redirect to TBOT for the base setup
